name: Deploy to Existing Lambda

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy to Existing Lambda
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Install dependencies (if any)
        run: npm install

      - name: Create ZIP file
        run: |
          zip -r lambda-function.zip index.js package.json
          # Include any additional files if needed

      - name: Deploy to Existing Lambda
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: |
          aws lambda update-function-code \
            --function-name dev-MyLambdaFunction \
            --zip-file fileb://lambda-function.zip \
            --region ap-south-1
