AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: AWS SAM Template for a Node.js Lambda function

Parameters:
  Env:
    Type: String
    Description: Environment name (e.g., prod, dev, stage)
    Default: stage

Resources:
  MyLambdaFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub '${Env}-MyLambdaFunction'
      Handler: index.handler
      Runtime: nodejs14.x
      CodeUri: ./index.js # Path to your Node.js Lambda function code
      Timeout: 10  # Maximum execution time in seconds
      Environment:
        Variables:
          ENVIRONMENT: !Ref Env

Outputs:
  MyLambdaFunctionArn:
    Description: Lambda Function ARN
    Value: !GetAtt MyLambdaFunction.Arn
  MyLambdaFunctionName:
    Description: Lambda Function Name
    Value: !Ref MyLambdaFunction
